janitrapp/urls.py
from django.urls import path
from . import views

#url for app
app_name = 'janitrapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('schedule/', views.my_schedule, name='my_schedule'),
    path('add-schedule/', views.add_schedule, name='add_schedule'),
    path('sched-form/', views.sched_form, name='sched_form'),
    path('delete/', views.delete_data, name='delete_data'),
] 

lab11/urls.py
from django.conf.urls import url
from django.urls import path
from .views import *

#url for app
app_name='lab11'
urlpatterns = [
    url(r'^$', login, name='login'),
    path('logout/', logout, name='logout'),
    path('signout/', signout, name='signout'),

]

lab6/urls.py
from django.conf.urls import url
from .views import add_status, profile
#url for app
app_name = 'lab6'
urlpatterns = [
    url(r'^$', add_status, name='add_status'),
    url(r'^add/$', add_status, name='add'),
    url(r'^profile/', profile, name='profile'),
]

lab9/urls.py
from django.conf.urls import url, include
from .views import index, data, get_data, add_to_favorites, remove_favorites
from django.contrib.auth import views
from django.conf import settings

#url for app
app_name = 'lab9'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^data/', data, name='data'),
    url(r'get_data/', get_data, name="get"),
    url(r'add/', add_to_favorites, name="add"),
    url(r'remove/', remove_favorites, name="remove"),
]

mysite/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('janitrapp.urls')),
    path('lab6/', include('lab6.urls')),
    path('lab9/', include('lab9.urls')),
    path('lab10/', include('lab10.urls')),
    path('lab11/', include('lab11.urls')), 
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab9/models.py
from django.db import models

# Create your models here.

lab9/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
import requests
import json
from django.contrib.auth import logout
from django.views.decorators.csrf import csrf_exempt



# Create your views here.
response = {}
def index (request):
    if not request.user.is_authenticated:
        HttpResponseRedirect('/lab11/')
    if 'user_id' not in request.session.keys():
        return HttpResponseRedirect(reverse('login'))

    if 'books' in request.session.keys():
        list_book = request.session['books']
    else:
        id_info = id_token.verify_oauth2_token(token, requests.Request(), '1035338547832-lko28uh75hlfih40uoreld3o4k5o7937.apps.googleusercontent.com')
        if id_info['iss'] not in ['accounts.google.com', 'https://accounts.google.com']:
            raise ValueError('Wrong issuer.')

        user_id = id_info['sub']
        # name = id_info['name']
        email = id_info['email']
        request.session['user_id'] = user_id
        # request.session['name'] = name
        request.session['email'] = email
        request.session['books'] = []        
        # list_book = []

    response['name'] = request.session['name']
    # response['count'] = len(list_book)

    return render(request, "lab9.html", response)

def data(request):
    try: 
        q = request.GET['q']
    except:
        q = 'quilting'

    getJson = requests.get('https://www.googleapis.com/books/v1/volumes?q=' + q)
    jsonParse = json.dumps(getJson.json())
    return HttpResponse(jsonParse)

def get_data(request):
    if 'user_id' not in request.session.keys():
        return HttpResponseRedirect(reverse('login'))

    if "name" in request.session:
        if(request.method == 'GET'):
            if request.session["books"] is not None:
                response["message"] = request.session["books"]
        else:
            response["message"] = "NOT ALLOWED"
    else:
        response["message"] = ""
    return JsonResponse(response)

    # book_api_url = "https://www.googleapis.com/books/v1/volumes?q=quilting"
    # book_json = requests.get(book_api_url).json()
    # book_items = book_json['items']
    # book_list = []

    # for book in book_items:
    #     book_id = book['id']
    #     if book_id in request.session['books']:
    #         is_favorited = True
    #     else:
    #         is_favorited = False
    #     book_dict = {"url": book['volumeInfo']['imageLinks']['thumbnail'],
    #                  "title": book['volumeInfo']['title'], "authors": book['volumeInfo']['authors'][0],
    #                  "published": book['volumeInfo']['publishedDate'],
    #                  "id": book['id'], 'boolean': is_favorited}
    #     book_list.append(book_dict)
    # return JsonResponse({'data': book_list})

@csrf_exempt
def add_to_favorites(request):
    if 'user_id' not in request.session:
        return HttpResponseRedirect(reverse('login'))

    if request.method == 'POST':
        # book_id = request.POST['id']
        # if 'books' not in request.session.keys():
        #     request.session['books'] = [book_id]
        #     size = 1
        # else:
        #     books = request.session['books']
        #     books.append(book_id)
        #     request.session['books'] = books
        #     size = len(books)
        # return JsonResponse({'count': size, 'id': book_id})
        favs = request.session["books"]
        if request.POST["id"] not in favs :
            favs.append(request.POST["id"])
        request.session["books"] = favs
        response["message"] = len(favs)
        return JsonResponse(response)
    else:
        return HttpResponse("GET method is not allowed")

@csrf_exempt
def remove_favorites(request):
    if 'user_id' not in request.session:
        return HttpResponseRedirect(reverse('login'))

    if request.method == 'POST':
        # book_id = request.POST['id']
        # books = request.session['books']
        # books.remove(book_id)
        # request.session['books'] = books
        # size = len(books)
        # return JsonResponse({'count': size, 'id': book_id})
        favs = request.session["books"]
        if request.POST["id"] in favs :
            favs.remove(request.POST["id"])
        request.session["books"] = favs
        response["message"] = len(favs)
        return JsonResponse(response)
    else:
        return HttpResponse("GET method is not allowed")
        

lab9/templates/lab9.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" itemscope itemtype="http://schema.org/Article">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    <title>Library Book</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/lab9.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/web.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Montserrat Alternates' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Bad Script' rel='stylesheet'>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <script src="https://apis.google.com/js/platform.js?onload=onLoad" async defer></script>
    <script src="{% static 'js/lab9.js' %}"></script>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <meta name="google-signin-client_id" content="1035338547832-lko28uh75hlfih40uoreld3o4k5o7937.apps.googleusercontent.com">
   
</head>
<body>
  <script>
    function onLoad() {
      gapi.load('auth2', function() {
        gapi.auth2.init();
      });
    }
 
  </script> 
    <a href="{% url 'janitrapp:index' %}">
        <img src="{% static 'media/my_logo.png' %}" class="logo">
    </a>
    <header class="text-center">
        <h1>Favorites Books of the Month</h1>
        {% if name %}
        <h1 class="sub" style="color: #717171; padding-top: 2rem; font-size: 52px;">Hello, {{ name }}!</h1>
        
        <a href="{% url 'lab11:logout' %}"><button id="logout" onclick="signOut()" style="margin-top: 2rem;">LOGOUT</button></a>
        {% else %}
        <div class="g-signin2" style="padding: 20px; margin-left: 200px;" data-onsuccess="onSignIn"></div>
        {% endif %}
        <div class="bintang">
                <img src="{% static 'star.png' %}" alt="star" max-width="100px;" height="100px;">
                <div class="centered" id="counter">0</div>
        </div>
    </header>

    <div class="text-center" style="padding-top: 2%;">
		<input id="myInput" type="text" placeholder="Search for books..." value="">
    </div>

    <div class="tabel">
        <table id="demo" class="table table-light table-bordered table-hover">
                <thead>
                    <tr>
                        <th scope="col" style="text-align: center;">No</th>
                        <th scope="col" style="text-align: center;">Add to Favorites</th>
                        <th scope="col" style="text-align: center;">Cover</th>
                        <th scope="col" style="text-align: center;">Categories</th>
                        <th scope="col" style="text-align: center;">Title</th>
                        <th scope="col" style="text-align: center;">Authors</th>
                        <th scope="col" style="text-align: center;">Publisher</th>
                    </tr>
                </thead>
                <tbody></tbody>
        </table>
    </div>
    <script src="{% static 'js/lab11.js' %}"></script>
    <script>
        function signOut() {
        var auth2 = gapi.auth2.getAuthInstance();
        auth2.disconnect();
        window.location.href = "/lab11/";
        console.log('User signed out.');
        // auth2.signOut().then(function () {
        //     console.log('User signed out.');
        // });
      }
      </script>
</body>
</html>