janitrapp/urls.py
from django.urls import path
from . import views

#url for app
app_name = 'janitrapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('schedule/', views.my_schedule, name='my_schedule'),
    path('add-schedule/', views.add_schedule, name='add_schedule'),
    path('sched-form/', views.sched_form, name='sched_form'),
    path('delete/', views.delete_data, name='delete_data'),
] 

lab6/urls.py
from django.conf.urls import url
from .views import add_status, profile
#url for app
app_name = 'lab6'
urlpatterns = [
    url(r'^$', add_status, name='add_status'),
    url(r'^add/$', add_status, name='add'),
    url(r'^profile/', profile, name='profile'),
]

mysite/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('janitrapp.urls')),
    path('lab6/', include('lab6.urls')),
    path('lab9/', include('lab9.urls')),
    path('lab10/', include('lab10.urls')),
    path('lab11/', include('lab11.urls')), 
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab6/models.py
from django.db import models

# Create your models here.
# bikim models sesuai permintaan, trus makemigrations sm migrate biar masuk ke dtaabase
# terus bikin test

class Status(models.Model):
    status = models.TextField(max_length = 300)
    created_at = models.DateTimeField(auto_now_add = True)

lab6/forms.py
from django import forms
from .models import Status

class StatusForm(forms.Form):
    attrs = {
        'class': 'form-control',
        'placeholder': 'Apa statusmu?'
    }

    status = forms.CharField(label='Status', required=True, max_length=300, widget=forms.TextInput(attrs=attrs))

lab6/views.py
from django.shortcuts import render, redirect
from .models import Status
from .forms import StatusForm

# Create your views here.
# def index(request):
#     stats = Status.objects.all().values()
#     response = {}
#     response['form'] = StatusForm
#     return render(request, 'status.html', response)

def add_status(request):
    form = StatusForm(request.POST or None)
    if (request.method == 'POST'):
        if form.is_valid():
            status = request.POST.get("status")
            Status.objects.create(status=status)
            return redirect('lab6:add')
    stats = Status.objects.all().order_by("-id")
    response = {
        "stats" : stats,
        "form" : form,
    }
    return render(request, 'status.html', response)

def profile(request):
    response = {}
    return render(request, 'profile.html')

lab6/templates/profile.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Janitra Ariena</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Montserrat Alternates' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Dancing Script' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Bad Script' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="{% static 'css/web.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'js/jsqu.js' %}"></script>
  </head>

<body>
<div class="loader"></div>
<div class="about" id="2">
      <a href="{% url 'janitrapp:index' %}">
        <img src="{% static 'media/my_logo.png' %}" class="logo">
      </a>
      <h2 class="title">Introducing Me</h2>
      <p class="text">NPM: 1706979316</p>
      <p>
  
      </p>
      <div class="row">
        <div class="col-md-4">
          <h3 class="sub">About me</h3>
        
          <p class="text">
            I am an undergraduate student at Universitas Indonesia majoring in Computer Science. I like to listening some musics and watching some movies.		</p>
        </div>
        <div class="col-md-4 text-center">
          <img src="{% static 'media/id.jpg' %}" alt="Janitra Ariena Sekarputri" class="foto img-responsive center-img"/>
        </div>
        <div class="col-md-4">
          <div class="container-detail">
          <h3 class="sub">Details</h3>
          <p class="text">
            <strong class="id">Name:</strong><br />
            Janitra Ariena Sekarputri<br />
            <strong class="id">Birth of Date</strong><br />
            October 16th, 1999<br />
            <strong class="id">Nationality:</strong><br />
            Indonesia		</p>
          </div>
        </div>
      </div>
      </div>
      <div class="text-center">
        <a class="btn" style="background-color: #DD999E; color: #ffff; align-content: center; margin: 20px;" href="{% url 'lab6:add_status' %}" role="button">Click here to add your current status</a>
      </div>
    </div>

    <div class="row align-center">
        <form style="align-content: center" name="bgcolor form">Pick your color: 
            <select id="dropdown">
            <option value="#fff">Default
                <option value="#DAF6F0">Green Pastel
                <option value="#F2F2F2">Grey Pastel
                <option value="#EBC7D6">Pink Pastel
                <option value="#AACEED">Blue Pastel
                <option value="#E3C0B9">Brown Pastel    
            </select>
        </form>
    </div>

    <div id="accordion">
      <h3 class="sub" style="font-size: 40px; background-color: #DBDDDC;">Activity</h3>
      <div class="text text-center">
        <p>
        Working hard to get a S.Kom! Wish me luck!  
        </p>
      </div>

      <h3 class="sub" style="font-size: 40px; background-color: #DBDDDC;">Organizations and Experiences</h3>
      <div class="text text-center">
        <p>- Staff of Public Relation Open House Fasilkom 2017</p>
        <p>- Intern at Public Relation Bureau BEM Fasilkom 2017</p>
        <p>- HRD of Fundraising CGT Fasilkom 2018</p>
        <p>- Staff of Art and Culture of BEM Fasilkom 2018</p>
        <p>- Staff of Sponsorship COMPFEST X</p>
        <p>- Vice Person in Charge Event of Open House Fasilkom 2018</p>
      </div>
      <h3 class="sub" style="font-size: 40px; background-color: #DBDDDC;">Achievements</h3>
      <div class="text text-center">
        <p>
        Have done all story and challenges of PPW,
        to see more about my website visit janitraa.herokuapp.com
        </p>
      </div>
    </div>
</body>

lab6/templates/status.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello!</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Montserrat Alternates' rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="{% static 'css/lab7.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/web.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="{% static 'js/jsqu.js' %}"></script>
</head>

<body>
    <div class="loader"></div>
    <div class="container">
        <a href="{% url 'janitrapp:index' %}">
            <img src="{% static 'media/my_logo.png' %}" class="logo">
        </a>
        <div class="row">
            <h1>Hello, Apa kabar?</h1>
        </div>

        <div class="row">
            <form name="bgcolor form">Pick your color: 
                <select id="dropdown">
                <option value="#fff">Default
                    <option value="#DAF6F0">Green Pastel
                    <option value="#F2F2F2">Grey Pastel
                    <option value="#EBC7D6">Pink Pastel
                    <option value="#AACEED">Blue Pastel
                    <option value="#E3C0B9">Brown Pastel    
                </select>
            </form>
        </div>

        <div class="row">
            <br>
            <form>Wanna see my profile? Click 
                <a class="btn" style="background-color: #DD999E; color: #ffff;" href="{% url 'lab6:profile' %}" role="button">My Profile</a>
            </form>
        </div>

        <div class="row text-center">
            <div class="col-lg-12 col-md-12 col-sm-12" style="margin: 50px 0;" >
                <section>
                    <div class="box">
                        <form method="POST" action="{% url 'lab6:add_status' %}">
                        {% csrf_token %}
                        {{form}}
                        <br>
                        <button id ="submit" type="submit" class="btn" style="background-color: #DD999E; color: #ffff">Submit</button>
                        </form>
                    </div>
                </section>
            </div>
        </div>

        <div class="row text-center">
            <table style="width:100%; text-align: center;">
                <tr>
                    <th>All Status</th>
                    <th>Date</th>
                </tr>
                {% for i in stats %}
                <tr>
                    <td> {{ i.status }} </td>
                    <td> {{ i.created_at }} </td>
                </tr>
                {% endfor %}
            </table>
            <br><br><br><br>
            </div>
    </div>
</body>