janitrapp/urls.py
from django.urls import path
from . import views

#url for app
app_name = 'janitrapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('schedule/', views.my_schedule, name='my_schedule'),
    path('add-schedule/', views.add_schedule, name='add_schedule'),
    path('sched-form/', views.sched_form, name='sched_form'),
    path('delete/', views.delete_data, name='delete_data'),
] 

lab10/urls.py
from django.contrib import admin
from django.conf.urls import url
from .views import index, subscribe, validate_email, list_subscriber, unsubscribe

#url for app
app_name = 'lab10'
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^subscribe/', subscribe, name='subscribe'),
    url(r'^validate_email/', validate_email, name='validate_email'),
    url(r'^list_subscriber/', list_subscriber, name='list_subscriber'),
    url(r'^delete_subscriber/', unsubscribe, name='unsubscribe'),
    
]

lab11/urls.py
from django.conf.urls import url
from django.urls import path
from .views import *

#url for app
app_name='lab11'
urlpatterns = [
    url(r'^$', login, name='login'),
    path('logout/', logout, name='logout'),
    path('signout/', signout, name='signout'),

]

lab6/urls.py
from django.conf.urls import url
from .views import add_status, profile
#url for app
app_name = 'lab6'
urlpatterns = [
    url(r'^$', add_status, name='add_status'),
    url(r'^add/$', add_status, name='add'),
    url(r'^profile/', profile, name='profile'),
]

mysite/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('janitrapp.urls')),
    path('lab6/', include('lab6.urls')),
    path('lab9/', include('lab9.urls')),
    path('lab10/', include('lab10.urls')),
    path('lab11/', include('lab11.urls')), 
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/Web.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Janitra Ariena</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Montserrat Alternates' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Dancing Script' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Bad Script' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="{% static 'css/web.css' %}">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src= "{% static 'js/web.js' %}"></script>
  </head>

<body>
  <div class="home" id="1">
    <div class="navbar-frame">
      {% block navbar %}
      {% include "navbar.html" %}
      {% endblock %}
    </div>
    <div class="cover-photo">
        <h1 class="anit">Janitra Ariena Sekarputri</h1>
        <img src="{% static 'media/home.JPG' %}" class="bhome">    
    </div>
  </div>
  
  <div class="about" id="2">
      <h2 class="title">Introducing Me</h2>
    <p class="text">NPM: 1706979316</p>
    <p>

    </p>
    <div class="row">
      <div class="col-md-4">
        <h3 class="sub">About me</h3>
      
        <p class="text">
          I am an undergraduate student at Universitas Indonesia majoring in Computer Science. I like to listening some musics and watching some movies.		</p>
      </div>
      <div class="col-md-4 text-center">
        <img src="{% static 'media/id.jpg' %}" alt="Janitra Ariena Sekarputri" class="foto img-responsive center-img"/>
      </div>
      <div class="col-md-4">
        <div class="container-detail">
        <h3 class="sub">Details</h3>
        <p class="text">
          <strong class="id">Name:</strong><br />
          Janitra Ariena Sekarputri<br />
          <strong class="id">Birth of Date</strong><br />
          October 16th, 1999<br />
          <strong class="id">Nationality:</strong><br />
          Indonesia		</p>
        </div>
      </div>
    </div>
    </div>
  </div>

    <div class="photos" id="5">
        <h3 class="title" >Photos of Me</h3>
        <div class="slideshow-container">

          <!-- Full-width images with number and caption text -->
          <div class="mySlides fade item active">
            <div class="numbertext">1 / 6</div>
            <img src="{% static 'media/foto1.JPG' %}" style="width:100%">
          </div>
        
          <div class="mySlides fade">
            <div class="numbertext">2 / 6</div>
            <img src="{% static 'media/foto2.jpg' %}" style="width:100%">
          </div>
        
          <div class="mySlides fade">
            <div class="numbertext">3 / 6</div>
            <img src="{% static 'media/foto3.JPG' %}" style="width:100%">
          </div>
  
          <div class="mySlides fade">
              <div class="numbertext">4 / 6</div>
              <img src="{% static 'media/foto4.JPG' %}" style="width:100%">
          </div>
          
          <div class="mySlides fade">
              <div class="numbertext">5 / 6</div>
              <img src="{% static 'media/foto5.JPG' %}" style="width:100%">
          </div>
  
          <div class="mySlides fade">
              <div class="numbertext">6 / 6</div>
              <img src="{% static 'media/foto6.JPG' %}" style="width:100%">
          </div>
  
        
          <!-- Next and previous buttons -->
          <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
          <a class="next" onclick="plusSlides(1)">&#10095;</a>
        </div>
        <br>
      
        <!-- The dots/circles -->
        <div style="text-align:center">
          <span class="dot" onclick="currentSlide(1)"></span> 
          <span class="dot" onclick="currentSlide(2)"></span> 
          <span class="dot" onclick="currentSlide(3)"></span> 
          <span class="dot" onclick="currentSlide(4)"></span> 
          <span class="dot" onclick="currentSlide(5)"></span> 
          <span class="dot" onclick="currentSlide(6)"></span> 
        </div> 
    </div>
    
  <div class="contact" id="6">
    <h2 class="title">Contact Me</h2>
    <br>
    <br>

    <div class="row">
      <div class="col-md-6">
        <a href="http://ui.ac.id" target="_blank" class="text">
          <img src="{% static 'media/mail.svg' %}" class='icon'>
                   janitra.ariena@ui.ac.id				</a>
        <br>
        
        <a href="+6287888905656" target="_blank" class="text">
            <img src="{% static 'media/call.svg' %}" class='icon'>
              +62-878-8890-56-56				</a>
      </div>
      <div class="col-md-6">
            <a href="http://twitter.com/janitraarienaa" target="_blank" class="text">
              <img src="{% static 'media/twtr.png' %}" width= '82px' height= '74px'>
              janitraarienaa				</a>
            <br>

            <a href="http://instagram.com/janitraasp" target="_blank" class="text">
              <img src="{% static 'media/ig.png' %}" width= '63.63px' height= '57.49px'>
              janitraasp				</a>
      </div>
      <div class='col-md-12'>
      <a href="http://linkedin.nl/in/janitra-ariena/" target="_blank" class="text">
        <img src="{% static 'media/in.svg' %}" class='icon'>
              http://linkedin.nl/in/janitra-ariena/				</a>
      <br>
      <a href="https://www.google.co.id/maps/place/Jakarta" target="_blank" class="text">
        <img src="{% static 'media/loc.svg' %}" class='icon'>
              Jakarta, Indonesia				</a>
      </div>
    </div>
  </div>

  <div class="message" id="7">
      <h2 class="title">Message Me</h2>
      <div class="container">
          <form action="action_page.php">
            <div class="row">
              <div class="col-md-12">
                  <label for="fname">Name</label>
                  <input type="text" id="fname" name="name" placeholder="Your name..">
              </div>
              <div class="col-md-12">
                  <label for="fdate">Date</label>
                  <input type="date" id="fdate" name="date">
              </div>
              <div class="col-md-12">
                  <label for="email">Email</label>
                  <input type="text" name="mail" placeholder="May I have your email please..">

              </div>
              <div class="col-md-12">
                  <label for="subject">Subject</label>
                  <textarea id="text" name="subject" placeholder="What do you want to say?"></textarea>
              
              </div>
              <div class="col-md-12">
                  <label for="pesan">Message</label>
                  <textarea id="text" name="subject" placeholder="Write something.." style="height:300px"></textarea>
              </div>
              <div class="col-md-12">
                  <input type="submit" value="Submit">
              </div>
              </form>
          </div>
      </div>
    </div>
  
        {% block content %}
        {% endblock %}
  

  </body>
</html>

templates/forms.html
{% extends "Web.html" %}
{% block content %}
<section name="add" style="padding-top: 95px">
    <h2 class="title">Add Schedule</h2>
    <form id="scheduleform" method="POST" action ="{% url 'janitrapp:add_schedule' %}">
        {% csrf_token %}
        {{forms.as_p}}
        <br>
        <button type="submit" class="btn" style="background-color: #DD999E; color: #ffff">Submit</button>
    </form>
</section>
{% endblock %}

templates/navbar.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Janitra Ariena</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Montserrat Alternates' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Dancing Script' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Bad Script' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="{% static 'css/web.css' %}">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src= "{% static 'js/web.js' %}"></script>
  </head>

<body>
    <div id="navbar">
      <nav style="width: 100%;" class="navbar navbar1 navbar-expand-lg navbar-light">
        <a href="{% url 'janitrapp:index' %}">
          <img src="{% static 'media/my_logo.png' %}" class="logo">
        </a>
        <button style="border: none;" class="navbar-toggler" onclick="show(event);" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'janitrapp:index' %}">ABOUT</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#5">GALLERY</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#6">CONTACT</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#7">MESSAGE</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  FEATURES
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'janitrapp:my_schedule' %}">SCHEDULE</a>
                  <a class="dropdown-item" href="{% url 'janitrapp:sched_form' %}">ADD SCHEDULE</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'lab6:add_status' %}">ADD STATUS</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'lab10:index' %}">SUBSCRIBE</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'lab11:login' %}">GOOGLE BOOKS</a>
                </div>
              </li>
          </ul>
        </div>
      </nav>
      
    </div>
    <div class="sched-form">
      {% block content %}
      {% endblock %}
    </div>
</body>

templates/schedule.html
{% extends "Web.html" %}
{% load static %}
{% block content %}
<div class="schedules" id="schedule">
    <h2 class="title">My Schedule</h2>
              <div class="col-md-12 text-center">
                <table style="width: 100%">
                    <thead>
                        <th>DATE</th>
                        <th>TIME</th>
                        <th>EVENT</th>
                        <th>PLACE</th>
                        <th>CATEGORY</th>
                    </thead>
                    <tbody>
                        {% for i in form_sched %}
                        <tr class = "warning">
                            <td> {{i.date}} </td>
                            <td> {{i.time}} </td>
                            <td> {{i.event_name}} </td>
                            <td> {{i.place}} </td>
                            <td> {{i.category}} </td>
                        {% endfor %}
                        </tr>
                    </tbody>
                </table>
                <br>
                <a href="{% url 'janitrapp:delete_data' %}"><button type="submit" class="btn" style="background-color: #DD999E; color: #ffff">Delete Schedule</button></a>
    </div>
</div>
{% endblock %}